rootProject.name = "MyLuaApp"
include(":app")
include(":editor")
include(":lua-lsp-server")
include(":builder")
include(":core")
include(":common")
include(":androlua")
include(":plugin")
include(":treeview")
include(":ide-api")
