include (":app")
rootProject.name = "MyLuaApp"
include (":editor")
include (":lua-lsp-server")
include (":tm4e")
include (":builder")
include (":core")
include (":common")
include (":luaj")
include(":androlua")
