---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/23 15:39
---

require "import"

--@type func
import {
  "android.app.*",
  "android.os.*",
  "android.widget.*",
  "android.view.*",
}

import "com.dingyi.MyLuaApp.R"
import "com.dingyi.MyLuaApp.databinding.PluginPermisssionLayoutBinding"


activity.setTheme(R.style.Theme_MyLuaApp)

--@type string
local path = tostring(...);

local permission_info = {
  ["GET_PACKAGE_SIZE"] = "计算应用存储空间";
  ["ACCESS_WIFI_STATE"] = "查看WLAN连接";
  ["WRITE_CONTACTS"] = "修改您的通讯录";
  ["READ_PHONE_STATE"] = "读取手机状态和身份";
  ["MANAGE_EXTERNAL_STORAGE"] = "android.permission.MANAGE_EXTERNAL_STORAGE";
  ["WRITE_CALL_LOG"] = "新建/修改/删除通话记录";
  ["BLUETOOTH_ADMIN"] = "访问蓝牙设置";
  ["REQUEST_INSTALL_PACKAGES"] = "请求安装文件包";
  ["SYSTEM_ALERT_WINDOW"] = "此应用可显示在其他应用上方";
  ["ACCESS_COARSE_LOCATION"] = "只有在前台运行时才能获取大致位置信息";
  ["READ_CONTACTS"] = "读取联系人";
  ["VIBRATE"] = "控制振动";
  ["SEND_SMS"] = "发送短信";
  ["ACCESS_FINE_LOCATION"] = "只能在前台获取精确的位置信息";
  ["CLEAR_APP_CACHE"] = "android.permission.CLEAR_APP_CACHE";
  ["WAKE_LOCK"] = "防止手机休眠";
  ["ACCESS_MEDIA_LOCATION"] = "从您的媒体收藏中读取位置信息";
  ["RECORD_AUDIO"] = "录音";
  ["ACCESS_BACKGROUND_LOCATION"] = "在后台使用位置信息";
  ["INTERNET"] = "拥有完全的网络访问权限";
  ["BIND_ACCESSIBILITY_SERVICE"] = "辅助功能";
  ["BATTERY_STATS"] = "android.permission.BATTERY_STATS";
  ["CHANGE_NETWORK_STATE"] = "更改网络连接性";
  ["ANSWER_PHONE_CALLS"] = "接听来电";
  ["SET_WALLPAPER"] = "设置壁纸";
  ["READ_LOGS"] = "android.permission.READ_LOGS";
  ["DOWNLOAD_WITHOUT_NOTIFICATION"] = "直接下载文件而不显示通知";
  ["CHANGE_WIFI_STATE"] = "连接WLAN网络和断开连接";
  ["KILL_BACKGROUND_PROCESSES"] = "关闭其他应用";
  ["READ_FRAME_BUFFER"] = "android.permission.READ_FRAME_BUFFER";
  ["ACCESS_NETWORK_STATE"] = "查看网络连接";
  ["WRITE_SMS"] = "android.permission.WRITE_SMS";
  ["BLUETOOTH"] = "与蓝牙设备配对";
  ["WRITE_EXTERNAL_STORAGE"] = "修改或删除您共享存储空间中的内容";
  ["READ_EXTERNAL_STORAGE"] = "读取您共享存储空间中的内容";
  ["CAMERA"] = "拍摄照片和视频";
  ["READ_SMS"] = "读取短信";
  ["INSTALL_SHORTCUT"] = "安装快捷方式";
  ["READ_CALL_LOG"] = "读取通话记录";
  ["FOREGROUND_SERVICE"] = "运行前台服务";
  ["WRITE_SETTINGS"] = "修改系统设置";
};

local permission_tab = {
};


--@type class
local databinding = PluginPermisssionLayoutBinding.inflate(LayoutInflater.from(this));
local list = databinding.list

activity.setContentView(databinding.root)
activity.setSupportActionBar(databinding.toolbar)
activity.getSupportActionBar().setTitle("权限编辑器")

list.setAdapter(ArrayAdapter(activity, android.R.layout.simple_list_item_multiple_choice))

list.setChoiceMode(ListView.CHOICE_MODE_MULTIPLE);

table.foreach(permission_info, function(k, v)
  table.insert(permission_tab, k)
  list.adapter.add(v)
end)

local function loadPermissionInLua()
  local app = {}
  load(io.readall(path), "", "bt", app)()
  local nowPermission = app.user_permission
  table.foreach(nowPermission, function(k, v)
    if table.find(permission_tab, v) then
      list.setItemChecked(table.find(permission_tab, v) - 1, true)
    end
  end)
end

local function dump(t)
  for k, v in ipairs(t) do
    t[k] = string.format("%q", v)
  end
  return table.concat(t, ",\n  ")
end

local function getPermissions()
  local result = {}
  table.foreach(permission_tab, function(k, v)
    if list.isItemChecked(k - 1) then
      --要-1防止遗漏
      table.insert(result, v)
    end
  end)
  return result
end

local function savePermissionInLua()
  local str = io.readall(path):match("(.+)user_permission")
  local permissionText = string.format("user_permission={\n  %s\n}", dump(getPermissions()))
  io.open(path, 'w+'):write(str .. permissionText):close()
end

if path:match("%.lua$") then
  loadPermissionInLua()
end

function onCreateOptionsMenu(menu)
  menu.add(activity.getString(R.string.save))
end

function onOptionsItemSelected()
  if path:match("%.lua$") then
    savePermissionInLua()
    activity.setResult(100)
    activity.finish()
  end
end

function onDestroy()
  onOptionsItemSelected()
end






