---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/23 1:54
--- The Lua no use Activity,you can't use some android api in it


console=require "console" --use console

function sendClassToLua(class,name)
    _G[tostring(name)]=class
end

function build(path,toPath)
    path,toPath=tostring(path),tostring(toPath)
    local _,suffix=string.match(path,'/(.+)%.(.+)$')
    if (suffix=="lua") then
        local ok,errorMsg=console.build(path)
        if ok then
            os.rename(path..'c',toPath)
        else
            return errorMsg
        end
    else
        local ok,errorMsg=console.build_aly(path)
        if ok then
            os.rename(path..'c',toPath)
        else
            return errorMsg
        end
    end
    return true
end


