---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/23 1:54
--- The Lua no use Activity,you can't use some android api in it


console=require "console" --use console

function sendClassToLua(class,name)
    _G[tostring(name)]=class
end

function build(path,toPath)
    path,toPath=tostring(path),tostring(toPath)
    local _,suffix=string.match(path,'/(.+)%.(.+)$')
    if (suffix=="lua") then
        local ok,errorMsg=console.build(path)
        if ok then
            os.rename(path..'c',toPath)
        else
            return errorMsg
        end
    else
        local ok,errorMsg=console.build_aly(path)
        if ok then
            os.rename(path..'c',toPath)
        else
            return errorMsg
        end
    end
    return true
end

function touint32(i)
    local code = string.format("%08x", i)
    local uint = {}
    for n in code:gmatch("..") do
        table.insert(uint, 1, string.char(tonumber(n, 16)))
    end
    return table.concat(uint)
end

function setXmlAppCode(pt,start,ends)
    pt,start,ends=tostring(pt),tostring(start),tostring(ends)
    local f = io.open(pt)
    local s = f:read("a")
    f:close()
    s = string.gsub(s, touint32(23), touint32(tointeger(ends) or 23),1)
    s = string.gsub(s, touint32(18), touint32(tointeger(start) or 18),1)

    local f = io.open(pt, "w")
    f:write(s)
    f:close()
end


